// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dujyflljecirgulzienx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR1anlmbGxqZWNpcmd1bHppZW54Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc1MTg2MjUsImV4cCI6MjA3MzA5NDYyNX0.-Y7LqlAt5bzH5-OxGtmhBxn3RWw4tU-PARfpDsXw3d8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});